# Generated by Django 3.1.7 on 2021-03-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
                ('Desination', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
            ],
            bases=('User.user',),
        ),
    ]
