# Generated by Django 3.1.7 on 2021-03-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinique',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
            ],
            bases=('User.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
                ('identifiant', models.IntegerField()),
                ('identifiantClinique', models.CharField(max_length=255)),
                ('Groupesanguin', models.CharField(max_length=255)),
                ('maladiechronique', models.CharField(max_length=255)),
            ],
            bases=('User.user',),
        ),
    ]
