# Generated by Django 3.1.7 on 2021-03-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_clinique_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_Clinique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
                ('medecin', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
            ],
        ),
    ]
