# Generated by Django 3.1.7 on 2021-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_patient_clinique'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, to='User.Patient'),
        ),
    ]
