# Generated by Django 3.1.7 on 2021-03-29 09:31

import User.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210323_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_clinique',
            name='Doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.doctor'),
        ),
        migrations.AlterField(
            model_name='patient_clinique',
            name='Patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.patient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.upload_path),
        ),
    ]
