# Generated by Django 3.1.6 on 2021-03-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210329_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Patients',
            field=models.ManyToManyField(to='User.Patient'),
        ),
    ]
